hosts:
  - localhost:8091
username: user
password: password
bucketName: dcp-test
metadata:
  config:
    bucket: dcp-test-meta
dcp:
  listener:
    bufferSize: 1000
  group:
    name: groupName
    membership:
      type: static
      memberNumber: 1
      totalMembers: 1
elasticsearch:
  typeName: _doc
  collectionIndexMapping:
    _default: indexname
  urls:
    - "http://localhost:9200"
  bulkSize: 1000
  bulkTickerDuration: 15s
checkpoint:
  type: manual