{
 "title": "Go DCP Elastic Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "DCP Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "cbgo_dcp_latency_ms_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "cbgo_process_latency_ms_current",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bulk Proess Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "cbgo_elasticsearch_connector_bulk_request_process_latency_ms_current",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DCP Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cbgo_lag_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mutation Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cbgo_mutation_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Deletion Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cbgo_deletion_totat", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Expiration Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cbgo_expiration_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rebalance Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cbgo_rebalance_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Member Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cbgo_total_members_current", "legendFormat": "{{app}}" }
   ]
  },
  {
   "title": "Offset Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "cbgo_offset_write_latency_ms_current",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connector Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "cbgo_elasticsearch_connector_latency_ms_current",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto - resident" }
   ]
  },
  {
   "title": "GO Memstats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytet", "legendFormat": "__auto - bytes allocated" },
    {
     "expr": "rate(go_memstats_alloc_bytes_total[30s])",
     "legendFormat": "__auto - alloc rate"
    },
    { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "__auto - stack inuse" },
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "__auto - heap inuse" }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes[$__range])",
     "legendFormat": "__auto - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes[$__range])",
     "legendFormat": "__auto - virtual"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GO Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes[$__range])",
     "legendFormat": "__auto - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total[$__range])",
     "legendFormat": "__auto - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes[$__range])",
     "legendFormat": "__auto - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes[$__range])",
     "legendFormat": "__auto - heap inuse"
    }
   ]
  },
  {
   "title": "Open FDS Deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "__auto: {{quantile}}" }
   ]
  }
 ]
}