name: 🔨 Build And Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          args: -c .golangci.yml --timeout=5m -v

      - name: Install dependencies
        run: go get .

      - name: Start Elasticsearch
        run: |
          docker-compose -f ./docker-compose.yml up -d

      - name: Test
        run: |
          go test -v ./...